.TH LIVE-MAGIC 1 "September 18, 2007"
.SH NAME
live-magic \- GUI configuration utility for creating Debian Live systems.
.SH SYNOPSIS
.B live-magic \<configuration_dir\>
.SH DESCRIPTION
Live-helper is a collection of programs that can be used to build Debian Live
system images. The philosophy behind live-helper is to provide a collection of
small, simple, and easily understood tools that can be used in your own program
to automate building of a Live system.
.PP
The \fBlive-magic\fP utility is a graphical user interface to live-helper that
features a wizard-based interface along with a more powerful graphical configuration
editor.
.SH AUTHOR
\fBlive-magic\fP was written by Chris Lamb <chris@chris-lamb.co.uk>.
